[package]
name = "erps-client"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
erps-proto = { path = "../proto" }
futures.workspace = true
tokio.workspace = true
tonic.workspace = true
uuid.workspace = true
thiserror.workspace = true
tokio-stream.workspace = true
